# Generated by Django 3.0.5 on 2020-04-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createacount',
            name='date',
            field=models.CharField(max_length=60),
        ),
    ]
