# Generated by Django 3.0.5 on 2020-04-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0003_auto_20200416_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.IntegerField(max_length=2000)),
                ('new_balance', models.IntegerField(max_length=2000)),
                ('date', models.CharField(max_length=500)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps1.CreateAcount')),
            ],
        ),
    ]
