# Generated by Django 3.0.5 on 2020-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0004_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='new_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='balance',
            name='old_balance',
            field=models.IntegerField(),
        ),
    ]
